name: PHP Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: PHP Syntax Check
      run: find . -type f -name '*.php' -exec php -l {} \;
